name: aku_dimana
description: Apps sederhana untuk mendeteksi lagi dimana

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  share: ^2.0.4
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "img/logo.png"

flutter:
  uses-material-design: true

